Forum/Controllers/CategoryController.cs
namespace Forum.Controllers
{
    using Forum.Data;
    using Forum.Models;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;
    using System.Linq;

    public class CategoryController : Controller
    {
        private readonly ForumDbContext context;

        public CategoryController(ForumDbContext context)
        {
            this.context = context;
        }

        [HttpGet]
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public IActionResult Create(Category category)
        {
            var authorId = context
                .Users
                .Where(x => x.UserName == this.User.Identity.Name)
                .First()
                .Id;
            category.AuthorId = authorId;
            if (ModelState.IsValid)
            {
                context.Categories.Add(category);
                context.SaveChanges();
                TempData["Success"] = $"{User.Identity.Name} successfully add new category.";
                if (TempData["Topic"] != null)
                {
                    return RedirectToAction("Create", "Topic");
                }
                return RedirectToAction("Index", "Home");
            }

            return View(category);
        }

        [HttpGet]
        [Authorize]
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", "Home");
            }

            var category = context
                .Categories
                .Include(x => x.Author)
                .Include(x => x.Topics)
                .ThenInclude(x => x.Comments)
                .ThenInclude(x => x.Author)
                .Where(x => x.Id == id)
                .FirstOrDefault();

            if (category == null)
            {
                return RedirectToAction("Index", "Home");
            }

            var categories = context
                .Categories
                .Include(x => x.Topics)
                .ToList();
            ViewData["Categories"] = categories;
            return View(category);
        }

        [HttpGet]
        [Authorize]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", "Home");
            }

            var category = context.Categories.Where(x => x.Id == id).FirstOrDefault();

            if (category == null)
            {
                return RedirectToAction("Index", "Home");
            }

            return View(category);
        }

        [HttpPost]
        [Authorize]
        public IActionResult Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                var categoryFromDb = context
                    .Categories
                    .SingleOrDefault(x => x.Id.Equals(category.Id));

                if (categoryFromDb == null)
                {
                    return RedirectToAction("Index", "Home");
                }

                TempData["Success"] = $"{User.Identity.Name} successfully edit category {categoryFromDb.Name} to {category.Name}.";

                categoryFromDb.Name = category.Name;

                context.SaveChanges();
                return RedirectToAction("Index", "Home");
            }

            return View(category);
        }

        [HttpGet]
        [Authorize]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index", "Home");
            }

            var category = context
                .Categories
                .Where(x => x.Id == id)
                .FirstOrDefault();

            if (category == null)
            {
                return RedirectToAction("Index", "Home");
            }

            return View(category);
        }

        [HttpPost]
        [Authorize]
        public IActionResult Delete(int id)
        {
            var category = context
                .Categories
                .Where(x => x.Id == id)
                .FirstOrDefault();

            if (category == null)
            {
                return RedirectToAction("Index", "Home");
            }

            TempData["Success"] = $"{User.Identity.Name} successfully delete category - {category.Name}.";
            context.Categories.Remove(category);
            context.SaveChanges();

            return RedirectPermanent("/");
        }
    }
}

Forum/Controllers/CommentController.cs
namespace Forum.Controllers
{
    using Forum.Data;
    using Forum.Models;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.EntityFrameworkCore;
    using System;
    using System.Linq;

    public class CommentController : Controller
    {
        private readonly ForumDbContext context;

        public CommentController(ForumDbContext context)
        {
            this.context = context;
        }

        [Authorize]
        [HttpGet]
        [Route("/Topic/Details/{id}/Comment/Create")]
        public IActionResult Create(int id)
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        [Route("/Topic/Details/{TopicId}/Comment/Create")]
        public IActionResult Create(Comment comment)
        {
            if (ModelState.IsValid)
            {
                comment.CreatedDate = DateTime.Now;
                comment.LastUpdatedDate = DateTime.Now;

                string authorId = context
                    .Users
                    .Where(x => x.UserName == User.Identity.Name)
                    .FirstOrDefault()
                    .Id;

                comment.AuthorId = authorId;

                Topic topic = this.context.Topics.Find(comment.TopicId);
                topic.LastUpdatedDate = DateTime.Now;

                context.Comments.Add(comment);

                context.SaveChanges();

                TempData["Success"] = $"{User.Identity.Name} successfully add comment.";

                return Redirect($"/Topic/Details/{comment.TopicId}");
            }
            return View(comment);
        }

        [Authorize]
        [HttpGet]
        [Route("/Topic/Details/{TopicId}/Comment/Edit/{id}")]
        public IActionResult Edit(int? topicId, int? id)
        {
            if (id == null)
            {
                return RedirectPermanent($"/Topic/Details/{topicId}");
            }

            Comment comment = context
                .Comments
                .Include(x => x.Author)
                .Include(x => x.Topic)
                .ThenInclude(t => t.Author)
                .FirstOrDefault(c => c.CommentId == id);

            if (comment == null)
            {
                return RedirectPermanent($"/Topic/Details/{topicId}");
            }
            return View(comment);
        }

        [Authorize]
        [HttpPost]
        [Route("/Topic/Details/{TopicId}/Comment/Edit/{id}")]
        public IActionResult Edit(Comment comment)
        {
            if (ModelState.IsValid)
            {
                var commentFromDb = context
                    .Comments
                    .Include(c => c.Author)
                    .FirstOrDefault(x => x.CommentId.Equals(comment.CommentId));

                if (commentFromDb == null)
                {
                    return RedirectPermanent($"/Topic/Details/{comment.TopicId}");

                }

                commentFromDb.Description = comment.Description;
                commentFromDb.LastUpdatedDate = DateTime.Now;

                context.SaveChanges();

                TempData["Success"] = $"{User.Identity.Name} successfully edit comment.";

                return Redirect($"/Topic/Details/{comment.TopicId}");
            }
            return View(comment);
        }

        [Authorize]
        [HttpGet]
        [Route("/Topic/Details/{TopicId}/Comment/Delete/{id}")]
        public IActionResult Delete(int topicId, int? id)
        {
            if (id == null)
            {
                return RedirectPermanent($"/Topic/Details/{topicId}");
            }

            var comment = context
                .Comments
                .Include(x => x.Author)
                .Include(x => x.Topic)
                .ThenInclude(t => t.Author)
                .FirstOrDefault(c => c.CommentId == id);

            if (comment == null)
            {
                return RedirectPermanent($"/Topic/Details/{topicId}");
            }

            return View(comment);
        }


        [Authorize]
        [HttpPost]
        [Route("/Topic/Details/{TopicId}/Comment/Delete/{id}")]
        public IActionResult Delete(int id)
        {
            var comment = context
                .Comments
                .Find(id);

            if (comment != null)
            {
                var topic = context.Topics.Find(comment.TopicId);
                topic.LastUpdatedDate = DateTime.Now;
                context.Comments.Remove(comment);
                context.SaveChanges();
            }
            TempData["Success"] = $"{User.Identity.Name} successfully delete comment.";

            return RedirectPermanent($"/Topic/Details/{comment.TopicId}");
        }
    }
}

Forum/Views/Shared/_CreateCategory.cshtml
<p>
    <a asp-controller="Category" asp-action="Create" class="btn btn-default">Create New Category</a>
</p>

Forum/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Forum</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/custom.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Forum</a>
            </div>
            <div class="navbar-collapse collapse">
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Forum</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Forum/Views/Shared/_List.cshtml
@model Topic

@{
    ViewData["Title"] = "Details";
}

<h2>Comments</h2>

<p>
    <a asp-controller="Comment" asp-action="Create" class="btn btn-default">Add Comment</a>
</p>

<div>
    @foreach (var comment in Model.Comments)
    {
        <article class="forum-post post-item highlighted-post">
            <div class="head-post table-holder">
                <div class="post-content">
                    <div>
                        <p>@comment.Description</p>
                    </div>
                    <div class="meta-info table-holder meta-details">
                        <div class="table-holder">
                            <div class="row">
                                <div class="cell">
                                    <span class="item-wrap date-wrap">
                                        <i class="fa fa-calendar">Created at: </i>
                                        <span class="post-date" title="Create at">
                                            @comment.CreatedDate.ToString("HH:mm dd/MMM/yyyy")
                                        </span>
                                    </span>
                                    <span class="item-wrap category-wrap">
                                        <i class="fa fa-exchange">Last Redaction: </i>
                                        <span class="date-time cell" title="Last Redaction">@comment.LastUpdatedDate.ToString("HH:mm dd/MMM/yyyy")</span>
                                    </span>
                                    <span class="item-wrap">
                                        <i class="fa fa-calendar">Author: </i>
                                        <span class="post-date" title="Author">
                                            @comment.Author.UserName
                                        </span>
                                    </span>
                                    <span class="item-wrap">
                                        @if (comment.IsAuthor(User.Identity.Name))
                                        {
                                            <a href="/Topic/Details/@ViewContext.RouteData.Values["id"]/Comment/Edit/@comment.CommentId" class="btn btn-default">Edit</a>
                                        }
                                        @if (comment.IsAuthor(User.Identity.Name) || comment.IsTopicAuthor(User.Identity.Name))
                                        {
                                            <a href="/Topic/Details/@ViewContext.RouteData.Values["id"]/Comment/Delete/@comment.CommentId" class="btn btn-default">Delete</a>
                                        }
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </article>
    }
</div>